# Generated by Django 4.0.6 on 2022-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
